"""
Django settings for fastroutecomputing_platform project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q!kd%gb7ja2x=)wk%5@6!kto4-7oa_5k(-xe(ag(5&yo2#hl)-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'fastroute',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fastroutecomputing_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fastroutecomputing_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

CONDITION = {
    "start_point": {
        "lat":0,
        "lng":0
    },
    "end_point": {
        "lat":0,
        "lng":0
    },
    "route":"osrm",
    "weather":"normal",
    "scan":"false"
}
ROUTE = {
    "code":200,
    "start_point": [],
    "end_point": [],
    "geometries": {
        "route":[],
        "options":[],
        "blocks_scan": [],
        "duration": 0,
        "distance": 0,
        "weather": "normal"
    },
}
# V1
SET_NUM_DRIVER_TO_SCAN = 6
SET_NUM_DRIVER_TO_GET_MAX_SPEED = 3
DEFAULT_SPEED = 60
KEY_GRAPH = ["0dc4f299-a491-452f-97e0-515c296c9453", "LijBPDQGfu7Iiq80w3HzwB4RUDJbMbhs6BU0dEnn","a948c182-388d-48eb-889f-01131bbce681","8fcdb3be-5de1-46db-b97f-a76370ca35b8","a3d9f382-aa47-49b2-bcc2-fda39e4c1dcc"]

# V2
VERSION_WAZE = "4.0.0"
start_point = "x%3A{}%20y%3A{}".format(CONDITION["start_point"]["lng"],CONDITION["start_point"]["lat"])
end_point = "x%3A{}%20y%3A{}".format(CONDITION["end_point"]["lng"], CONDITION["end_point"]["lat"])
URLROUTE = "https://www.waze.com/row-RoutingManager/routingRequest?at=0&clientVersion={}&from={}&nPaths=3&options=AVOID_TRAILS%3At%2CALLOW_UTURNS%3At&returnGeometries=true&returnInstructions=true&returnJSON=true&timeout=60000&to={}".format(VERSION_WAZE, start_point, end_point)
URLTRAFFIC = "https://www.waze.com/row-rtserver/web/TGeoRSS?bottom={}&left={}&ma=200&mj=100&mu=20&right={}&top={}types=alerts%2Ctraffic%2Cusers".format(CONDITION["start_point"]["lng"], CONDITION["start_point"]["lat"],CONDITION["end_point"]["lng"],CONDITION["end_point"]["lng"])
HEADER = {
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5",
    "referer": "https://www.waze.com/livemap/directions?q=66%20Acacia%20Avenue&navigate=yes&latlng={}%2C-{}".format(CONDITION["start_point"]["lng"], CONDITION["start_point"]["lat"]),
}